Add files via upload

diff --git a/proyecto_1 b/proyecto_1
--- a/proyecto_1
+++ b/proyecto_1
@@ -1,5 +1,8 @@
 #! /bin/bash
 
+psql -d fdd2db -c "drop table if exists purchase_carts;drop table if exists book_user"
+#psql -d fdd2db -c "drop table if exists purchase_carts"
+
 # Crear tabla Catalog
 psql -d fdd2db -c "create table if not exists catalog (bookshelf_id serial primary key, title varchar(70), url varchar(50))"
 
@@ -35,16 +38,30 @@ total_bookshelves=$(psql -d fdd2db -c "select count(bookshelf_id) from catalog" 
 read -p "Enter a number of bookshelves between [1-$total_bookshelves]	" n
 user_bookshelves=${n:-10}
 
+if (( $user_bookshelves > $total_bookshelves )) || (( $user_bookshelves < 1 ))
+then
+echo "Error, enter a number of bookshelves between [1-$total_bookshelves]"
+exit
+fi
+
 psql -d fdd2db -c "drop table if exists books_user_i"
 psql -d fdd2db -c "create table books_user_i as (select * from book where bookshelf_id <= $user_bookshelves)"
 total_downloads=$(psql -d fdd2db -c "select sum(downloads) from books_user_i" | awk '/ [0-9]+/ { print 1/$1}')
-psql -d fdd2db -c "drop table if exists book_user"
-psql -d fdd2db -c "create table book_user as (select book_id, bookshelf_id, title,author,url, downloads, sum_downloads, sum_downloads*$total_downloads as percentile from (select *, sum(downloads) over (order by downloads rows between unbounded preceding and current row) as sum_downloads from (select * from books_user_i) as sbq1) as sbq2)"
+
+psql -d fdd2db -c "create table book_user as (select book_id, bookshelf_id, title,author,url, downloads, sum_downloads, sum_downloads*$total_downloads as percentile from (select *, sum(downloads) over (order by downloads desc rows between unbounded preceding and current row) as sum_downloads from (select * from books_user_i) as sbq1) as sbq2)"
 psql -d fdd2db -c "drop table if exists books_user_i"
 
+psql -d fdd2db -c "alter table book_user add constraint pk_book primary key (book_id)"
+
 # Simulate user behaviour
-read -p "Enter a number of users between [1, 10000]	" m
+read -p "Enter a number of users between [1-10000]	" m
 num_user=${m:-1000}
+
+if (( $num_user > 10000 )) || (( $num_user < 1 ))
+then
+echo "Error, enter a number of users between [1-10000]"
+exit
+fi
 
 psql -d fdd2db -c "drop table if exists users; create table if not exists users(user_id serial primary key, name varchar(15))"
 for i in $(seq $num_user)
@@ -55,16 +72,20 @@ psql -d fdd2db -c "$query"
 done
 
 now=$(date +'%Y-%m-%d')
+psql -d fdd2db -c "create table purchase_carts(cart_id integer, user_id integer, book_id integer references book_user(book_id), purchase_date date, percentile float, constraint pk_purchase_cart primary key(cart_id, user_id, book_id))"
 
 for i in $(seq $num_user)
 do
 rand_num_books=$(( $RANDOM%10 + 1 ))
 echo $rand_num_books
+rand_date=$(shuf -n1 -i$(date -d '2020-01-01' '+%s')-$(date -d $now '+%s') | xargs -I{} date -d '@{}' '+%Y/%m/%d')
 for book in $(seq $rand_num_books)
 do
-rand_date=$(shuf -n1 -i$(date -d '2020-01-01' '+%s')-$(date -d $now '+%s') | xargs -I{} date -d '@{}' '+%d/%m/%Y')
-rand_book_id=$(psql -d fdd2db -c "select book_id from book_user order by random() limit 1" | awk '/ [0-9]+/{print $0}')
-rand_bookshelf=$(psql -d fdd2db -c "select bookshelf_id from book_user where book_id=$rand_book_id" | awk '/ [0-9]+/{print $0}')
+rand_book_id=$(psql -d fdd2db -c "select book_id from book_user order by random() limit 1" | awk '/ [0-9]+/{print $1}')
+#rand_bookshelf=$(psql -d fdd2db -c "select bookshelf_id from book_user where book_id=$rand_book_id" | awk '/ [0-9]+/{print $1}')
+percentile=$(psql -d fdd2db -c "select percentile from book_user where book_id=$rand_book_id" | awk '/ 0\.[0-9]+/{print $1}')
+psql -d fdd2db -c "insert into purchase_carts values(1, $i, $rand_book_id, cast('$rand_date' as date), $percentile)"
+done
+done
 
-done
-done
+psql -d fdd2db -c "select * from purchase_carts" | grep -iE '^ +[0-9]+' | sed -e 's/|/,/g' -e 's/ //g' > purchase_carts.csv
